export const endProccessConstants = {
    LEGAL_PERSON_DECLARATION: 'LEGAL_PERSON_DECLARATION',
    ONP_PENSIONER_DECLARATION: 'ONP_PENSIONER_DECLARATION',
    NO_BENEFICIARIES_DECLARATION: 'NO_BENEFICIARIES_DECLARATION',
    UNEMPLOYMENT_CONDITION_DECLARATION: 'UNEMPLOYMENT_CONDITION_DECLARATION'
}