export const ADVISOR_UI_SET_MESSAGE = 'ADVISOR_UI_SET_MESSAGE';
export const ADVISOR_UI_SET_LOADING = 'ADVISOR_UI_SET_LOADING';
export const ADVISOR_SET_DATA_NEW_BENEFICERY = 'ADVISOR_SET_DATA_NEW_BENEFICERY';
export const ADVISOR_SET_DJ_NO_BENEFICIARY = 'ADVISOR_SET_DJ_NO_BENEFICIARY';
export const ADVISOR_SET_VIEW_VIDEO = 'ADVISOR_SET_VIEW_VIDEO';
export const ADVISOR_SET_PENSIONER = 'ADVISOR_SET_PENSIONER';
export const ADVISOR_SET_CHECK_NO_RUC = 'ADVISOR_SET_CHECK_NO_RUC';