export const personalProcedures = {
  information: [
    {
      name: "Ahorros voluntarios",
      groupDescription: "Apertura de cuenta y plan flexible",
      type: "list",
      value: [
        "Apertura de cuentas de Aportes Voluntarios",
        "Cancelación de Plan Flexible",
      ],
    },
    {
      name: "Aportes",
      groupDescription: "Aportes de independiente, cambio de fondo y más",
      type: "list",
      value: [
        "Cambio de fondo",
        "Cargo en cuenta para tu aporte de independiente",
        "Actualización del Vínculo Laboral",
        "Inicio de Cobranza",
      ],
    },
    {
      name: "Bono de Reconocimiento",
      groupDescription: "Bonos y apelaciones",
      type: "list",
      value: [
        "Carta para la ONP",
        "Reconsideraciones y/o Apelaciones",
        "Trámite de Bono de Reconocmiento",
      ],
    },
    {
      name: "Desafiliación",
      groupDescription:
        "Desafiliación, nulidad, si estás afiliado a 2 AFP y más",
      type: "list",
      value: [
        "Denuncia al promotor",
        "Desafiliación",
        "Multiafiliación",
        "Nulidad",
      ],
    },
    {
      name: "Desistimiento de trámite",
      groupDescription: "Si ya no deseas continuar con tu trámite iniciado",
      type: "list",
      value: ["Desistimiento de trámites"],
    },
    {
      name: "Devolución de Aportes",
      groupDescription: "Afiliados, jubilados en otro régimen y más",
      type: "list",
      value: [
        "Devolución de Aportes de Afiliados",
        "Devolución de Aportes de Jubilados en otro regimen (Circular 040-2004)",
        "Devolución de Aportes por DU 037-94",
      ],
    },
    {
      name: "Invalidez",
      groupDescription:
        "Evaluación, pensión, apelaciones, inclusión de beneficiarios y más",
      type: "list",
      value: [
        "Evaluación y Calificación de Invalidez",
        "Revisión y/o Apelación de dictámenes",
        "Pensión de Invalidez",
        "Pensión de Jubilación Anticipada por Enfermedad Terminal o Cancer",
        "Retiro de hasta 50% de tu fondo por Enfermedad Terminal o Cancer",
        "Cambio de forma de pago",
        "Cambio de modalidad",
        "Convenio Perú-España, Ibero 1-CM ISS",
        "Exclusión de beneficiarios",
        "Inclusión de beneficiarios",
        "Regimen Pesquero",
        "Repacto de pensión",
        "Pensión por recupero de aportes en cobranza",
      ],
    },
    {
      name: "Jubilación",
      groupDescription: "",
      type: "list",
      value: [
        "Fondo Complementario de Jubilación Minera, Metalúrgica y Siderúrgica",
        "Pensión Complementaria de Pensión Mínima",
        "Pensión de Jubilación Anticipada Ordinaria",
        "Pensión de Jubilación Anticipada por Enfermedad Terminal o Cancer",
        "Pensión de Jubilación Anticipada por desempleo",
        "Pensión de Jubilación Labores de Riesgo Genérico",
        "Pensión de Jubilación Legal",
        "Pensión de Jubilación por Labores de Riesgo Extraordinario",
        "Pensión Mínima de Jubilación",
        "Reconsideraciones y/o Apelaciones",
        "Cambio de forma de pago",
        "Cambio de Modalidad",
        "Convenios Perú-España, Ibero 1-CM ISS",
        "Exclusión de beneficiarios",
        "Inclusión de beneficiarios",
        "Regimen Pesquero",
        "Repacto de pensión",
        "Pensión por recupero de aportes en cobranza",
      ],
    },
    {
      name: "Requerimientos",
      groupDescription: "Actualización de datos, estado de cuenta y más",
      type: "list",
      value: [
        "Actualización de datos",
        "Actualización de datos de beneficiarios",
        "Certificado de Afiliación",
        "Certificado de Pensionista",
        "Certificado de Supervivencia",
        "Constancia de 4.5% - ESSALUD",
        "Constancia de 95.5%",
        "Contrato de Afiliación",
        "Envío de Boletas de Pago",
        "Estado de Cuenta",
      ],
    },
    {
      name: "Retiro de Aportes",
      groupDescription: "Retiro hipotecario y más",
      type: "list",
      value: [
        "Retiro de hasta 50% de tu fondo por Enfermedad Terminal o Cancer",
        "Retiro 25% Hipotecario",
        "Retiro Aportes Voluntarios Sin Fin Previsional",
        "Retiro de hasta el 100%",
        "Transferencias de Fondos al Exterior",
      ],
    },
    {
      name: "Sobrevivencia",
      groupDescription: "Gastos de sepelio, herencias, pensiones y más",
      type: "list",
      value: [
        "Aviso de Siniestro",
        "Gastos de Sepelio",
        "Herencia",
        "Pensión de Sobrevivencia",
        "Cambio de forma de pago",
        "Cambio de Modalidad",
        "Exclusión de beneficiarios",
        "Inclusión de beneficiarios",
        "Regimen Pesquero",
        "Repacto de Pensión",
        "Pensión por Recupero de aportes en cobranza",
      ],
    },
  ],
};