apiVersion: v1
kind: Service
metadata:
  name: prima-new-pac-app-service
spec:
  type: LoadBalancer
  selector:
    app: prima-new-pac-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
