export const ErrorMessages = {
    verifyYourDocument: 'Verifica tu documento o nº de documento',
    verifyYourEmail: 'Verifica tu correo electrónico',
    minSize5Characters: 'Recuerda, tu número de documento debe tener mínimo 5 carácteres',
    maxSize12Characters: 'Recuerda, tu número de documento debe tener máximo 12 carácteres',
    onlyAlphanumericCharacters: 'Sólo se aceptan valores alfanuméricos',
    fixedSize8Characters: 'Recuerda, tu número de documento debe tener 8 carácteres.',
    includeNumberInPass: 'Por favor, incluye números en tu contraseña',
    includeLettersInPass: 'Por favor, incluye letras en tu contraseña',
    enterYourDocumentNumber: 'Por favor, ingresa tu Nº de documento',
    createPassword: 'Por favor, crea una contraseña',
    passwordMaxSize: 'Recuerda que tu contraseña debe tener máximo 20 carácteres',
    passwordMinSize: 'A tu contraseña le hacen falta carácteres, recuerda que debe tener al menos 8.',
    enterYourEmail: 'Por favor, ingresa tu correo electrónico',
    emailMaxSize: 'Recuerda, tu email debe tener máximo 50 carácteres.',
    includeCharacterOnEmail: 'Por favor, incluye un “@“ en el correo electrónico',
    fatherLastnameRequired: 'Por favor, ingresa tu apellido paterno',
    motherLastnameRequired: 'Por favor, ingresa tu apellido materno',
    firstNameRequired: 'Por favor, ingresa tu apellido materno',
    fatherMaxSize: 'Recuerda, tu apellido paterno debe tener máximo 25 carácteres',
    motherMaxSize: 'Recuerda, tu apellido materno debe tener máximo 25 carácteres',
    firstNameMaxSize: 'Recuerda, tu primer nombre debe tener máximo 25 carácteres',
    secondNameMaxSize: 'Recuerda, tu segundo nombre debe tener máximo 25 carácteres',
    verifyYourFatherSurname: 'Verifica tu apellido paterno',
    verifyYourMotherSurname: 'Verifica tu apellido materno',
    verifyYourFirstName: 'Verifica tu primer nombre',
    verifyYourSecondName: 'Verifica tu segundo nombre',
    birthdateRequired: 'Por favor, ingresa tu fecha de nacimiento',
    verifyYourMovilPhone: 'Verifica tu número de teléfono movil',
    verifyYourTelephone: 'Verifica tu número de teléfono',
    birthdateFixedSize: 'Recuerda, tu fecha de nacimiento debe tener el siguiente formato dd/mm/yyyy.',
    movilPhoneRequired: 'Por favor, ingresa tu número de teléfono móvil',
    movilPhoneFixedSize: 'Por favor, completa tu número de teléfono móvil',
    telephoneRequired: 'Por favor, ingresa tu número de teléfono',
    telephoneFixedSize: 'Por favor, completa tu número de teléfono',
    addPointToEmail: 'Por favor, incluye un "." en el correo electrónico',
    movilPhoneExceededSize: 'Verifica tu número de teléfono movil',
    telephoneExceededSize: 'Verifica tu número de teléfono',
    invalidDate: 'La fecha proporcionada no es válida',
    verifyYourAccountNumber: 'Verifica tu Nro. de Cuenta',
    enterYoutAccountNumber: 'Por favor, indica un Nro. de Cuenta',
    accountNumberFixedSize: "Por favor, completa tu Nro. de Cuenta",
    enterYourtInterbankAccountNumber: 'Por favor, indica tu Nro. de Cuenta interbancara',
    enterYourInterbankAccountNumberMinSize: 'Por favor, completa tu Nro. de Cuenta interbancara',
    verifyYourInterbankAccountNumber: 'Verifica tu Nro. de Cuenta interbancara',
}