export const LEGAL_PERSON_DECLARATION = 'LEGAL_PERSON_DECLARATION'
export const ONP_PENSIONER_DECLARATION = 'ONP_PENSIONER_DECLARATION'
export const NO_BENEFICIARIES_DECLARATION = 'NO_BENEFICIARIES_DECLARATION'
export const UNEMPLOYMENT_CONDITION_DECLARATION = 'UNEMPLOYMENT_CONDITION_DECLARATION'