export const PROCEDURES_REQUEST = 'PROCEDURES_REQUEST';
export const SELECT_PROCEDURE = 'SELECT_PROCEDURE';
export const ADD_COMMENT_TO_NEW_REQUEST = 'ADD_COMMENT_TO_NEW_REQUEST';
export const ADD_BENEFICIARY_TO_NEW_REQUEST = 'ADD_BENEFICIARY_TO_NEW_REQUEST';
export const DELETE_BENEFICIARY_FROM_NEW_REQUEST = 'DELETE_BENEFICIARY_FROM_NEW_REQUEST';
export const EDIT_BENEFICIARY_FROM_NEW_REQUEST = 'EDIT_BENEFICIARY_FROM_NEW_REQUEST';
export const DELETE_ALL_BENEFICIARIES = 'DELETE_ALL_BENEFICIARIES';
