export enum EAfpErrorCode {
  AFP_ERR_CODE_VALIDATE_CLAVE_WEB = 'AFP3001',
  AFP_ERR_CODE_VALIDATE_RENIEC = 'AFP3002',
  AFP_ERR_CODE_LOCK_THREE_ATTEMPS_FAIL = 'AFP3003',
  AFP_ERR_CODE_INVALID_WEB_PWD = 'AFP3004',
  AFP_ERR_CODE_INVALID_WEB_PWD_GO_RENIEC = 'AFP3005',
  AFP_ERR_CODE_INVALID_RENIEC_ANSWERS = 'AFP3006',
}
