export enum EState {
  QUESTIONS = 'QUESTIONS',
  ANSWERS = 'ANSWERS',
  AMOUNT = 'AMOUNT',
  FLOW = 'FLOW',
  SUBFLOW = 'SUBFLOW',
  AMOUNT_WITHDRAW = 'AMOUNT_WITHDRAW',
  FILE_NAME = 'FILE_NAME',
  REQUEST_SUCCESS = 'REQUEST_SUCCESS',
  ACCOUNT_STATEMENT = 'ACCOUNT_STATEMENT',
}
