export const AFFILIATE_REQUEST = 'AFFILIATE_REQUEST';
export const AFFILIATE_SUCCESS = 'AFFILIATE_SUCCESS';
export const AFFILIATE_FAILURE = 'AFFILIATE_FAILURE';
export const AFFILIATE_EMPTY = 'AFFILIATE_EMPTY';